name: syntheory
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch
  - torchaudio
  - torchvision
  - ffmpeg=4.3
  - pip
  - pip:
    - huggingface-hub==0.22.2
    - "git+https://github.com/rodrigo-castellon/jukemirlib.git"
    - ffmpeg-python==0.2.0
    - matplotlib==3.9.1
    - mido==1.3.2
    - pandas==2.2.1
    - pytest==8.3.2
    - pytest-cov==5.0.0
    - ruff==0.5.5
    - torcheval==0.0.7
    - tqdm==4.45.0
    - transformers==4.39.3
    - wandb==0.17.0
    - zarr==2.17.1
variables:
  PYTHONPATH: .
